### ISSUE TITLE
Wrong version is displayed

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#102]
https://depot.haiku-os.org/ffmpeg
Current version of ffmpeg in x86_gcc2 @ haikuports is 0.10.14-3, however HDS shows version 0.11.5-2

**Comment by aplgithub** [comment]
If I look on the "All versions" link on the package then I can see that it has a number of "x86_gcc2" versions.  On 2014-10-24 there were two versions populated from the repository;

* ```ffmpeg - 0.11.5-1 - x86_gcc2 @ haikuports```
* ```ffmpeg - 0.11.5-2 - x86_gcc2 @ haikuports```

The version "0.10.14-3" was loaded later on 2015-04-27, but the ordering of the versions clearly puts the older one as the latest version.

This shows up in the system logs;

```
2015-11-21 21:55:56,534 -/- [job-run-0123..] WARN  o.h.h.pkg.PkgOrchestrationService - imported a package version 0.10.14-3 of ffmpeg wh
ich is older or the same as the existing 0.11.5-2
```

Also it was discussed on the mailing list under the subject "Re: [haiku-depot-web] Re: Update - Changelog and Adjusted Maintenance Tasks" on 2015-09-21.

Are those older versions incorrect?  If so, should they be deleted?

**Comment by diversys** [comment]
ffmpeg package was downgraded in http://cgit.haiku-os.org/haiku/commit/?id=hrev48084 so they should be probably be deleted. Can anything be done to prevent this in the future?

**Comment by aplgithub** [comment]
I have now deactivated those 0.11.5 versions off ffmpeg now.  This problem does show up in the logs so I will drop a note about those anomalies to the mailing list in case anybody knows about other issues.
