### ISSUE TITLE
Downloading hpkg files for 3d party repos seems broken

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#103]
These 2 packages are from 2 different repos and both can't be downloaded:
https://depot.haiku-os.org/arora
https://depot.haiku-os.org/soundplay

**Comment by aplgithub** [comment]
The application server is sending back a 302 response with a ```Location``` header set to the URL of the HPKG data straight off the remote repository.  Directly accessing the application server using ```http://`` works, but through the Apache load-balancer via ```https://```, the ```Location``` header is being modified.  In the case where the header is being modified, it starts off as;

```
http://clasquin-johnson.co.za/michel/repo/packages/arora-0.11.0-1-x86_gcc2.hpkg
```

...but is modified to...

```
https://depot.haiku-os.org/michel/repo/packages/arora-0.11.0-1-x86_gcc2.hpkg
```

I'm not yet sure why this is happening.

**Comment by aplgithub** [comment]
See [this](http://httpd.apache.org/docs/2.2/mod/mod_proxy.html) page look for "ProxyPassReverse"; looks like it is re-writing the ```Location``` header.  I'll see if I can get that to stop happening for the "/__pkgdownload" path.

**Comment by aplgithub** [comment]
Yes it does seem to be that which is the problem.  I've tried to create various "Location" blocks in the Apache config to circumvent the re-write of the ```Location``` header for this path including using regex, but I can't seem to get it to stop for this specific path.  What I will do instead is made an application-server level change to do an in-page redirect instead; not so nice, but it will work.

**Comment by aplgithub** [comment]
Done no; will be in the next deployment.

**Comment by aplgithub** [comment]
The solution I came up with was to alter the "src" on an IFRAME to point to the HPKG and then the browser would initiate the download.  This failed because the browser is not happy to switch from HTTPS to HTTP which I only remembered when it was deployed in 1.0.62 just deployed.  I'll have to revisit this one again.

**Comment by aplgithub** [comment]
Should be sorted now.

**Comment by diversys** [comment]
Downloading works now but weirdly enough, there is no tooltip with full url when I move cursor over "Download package 'hpkg' file" link.

**Comment by aplgithub** [comment]
Should be sorted now; next deploy.
