### ISSUE TITLE
Determination of latest package not always correct

### ISSUE THREAD

**Issue by Perelandra0x309** [aplgithub/haikudepotserver#111]
It looks like the code determines the latest package by alphabetical sorting of the file name, but this is not always correct.  For example Einsteinium was initially added with a different naming scheme than the version number, so even though newer version have been added the first package added is still listed as the "Latest". See https://depot.haiku-os.org/#/pkg/einsteinium
Maybe add a check of the Created date/time value and if the latest as determined alphabetically does not match the latest determine by date/time flag it, or just let the date/time be the determining value.

**Comment by aplgithub** [comment]
Hello; the sorting is determined by the java class ```VersionCoordinatesComparator``` within a given architecture.  This simulates the C/C++ behavior in the operating system itself by using the java ```NaturalStringComparator``` on the major, minor and micro elements of the version and simple natural-ordering on the pre_release and revision.   See ```BPrivate::NaturalCompare(..)``` for the C/C++ corollary.  So the sorting of versions _should_ correlate to the operating system's sorting.

Here are those package versions' components in the sort-order shown in HDS;

|major|minor|micro|pre_release|revision|
|---|---|---|---|---|
|1|2|-|-|1|
|1|3|0|-|1|
|20141023|-|-|-|2|

The sort ordering is;

# major
# minor
# micro
# pre_release
# revision

I think following the algorithm this seems to be sound.  Can you please highlight where in the algorithm you see a problem arising?

**Comment by aplgithub** [comment]
This problem is happening with this package on import;

```
2016-11-01 02:24:03,860 / [job-run-4396..] WARN  o.h.h.pkg.PkgOrchestrationService - imported a package version 1.3.0-1 of einsteinium which is older or the same as the exist
ing 20141023-2
```

See the discussion on the mailing-list.

**Comment by Perelandra0x309** [comment]
I just read the mailing list and yes it looks like a couple things are happening, whether user error or downgrading versions or having multiple releases under the same package name.  With einsteinium this was initially put on the haikuporter with an incorrect major version.  This version's recipe has since been removed from haikuporter, and I don't know how a package transfers from haikuporter to the depot, but it looks like a removal of a recipe on haikuporter is not detected by the depot server.
Is there a way to report package issues on the depot website?  Not back-end code issues, but something like this where a package is incorrect or something like the "Active" status is incorrect?  I could not find a way.

**Comment by Perelandra0x309** [comment]
Here are the current versions of einsteinium on haikuports
https://github.com/haikuports/haikuports/tree/master/haiku-apps/einsteinium

**Comment by aplgithub** [comment]
I think this should be sorted out now by disabling the erroneous version.

**Comment by Perelandra0x309** [comment]
How long do updates normally take?  The 20141023 version was still on the Depot a few days ago but was taken off Haikuports on Sept 17.  Also the newest 1.3.1 version is not up yet.
https://github.com/haikuports/haikuports/commit/29d3c8e2e71fc781aabaad38d7bd842327f70e42#diff-37124e134a41782d94ccac292f9f68c0

**Comment by aplgithub** [comment]
It seems that I can see version `1.3.0-1` of the package `einsteinium`.

The intention is that external systems will use the [API](https://depot.haiku-os.org/__docs/ch13.html#api-importrepositorydata) on HaikuDepotServer (HDS) to trigger a refresh.  However some repository owners don't have time and/or inclination to set that up so HDS will also perform a refresh once per day.
