### ISSUE TITLE
Uploading non-ASCII filenames

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#113]
When trying to upload files (icon or screenshot) with special characters in their filename, HDS refuses to do so, saying it's too large. The test filename here was "AüöK.hvif".

Screenshot: https://s11.postimg.org/jcw7uy51d/Umlaut_fun.png

**Comment by aplgithub** [comment]
Hi Humdinger - are you able to note the browser and platform?  Do you experience the same problems on other browsers?  Is there anything indicative in the browser console?

**Comment by humdingerb** [comment]
The error appears with the latest Web+. QupZilla has no problems, it shows the correct filename with (truncated) path. Note that in the screenshot Web+ error the "Store Icons" button isn't even enabled. To be specific, the error appears after selecting the file in the open dialog, not actually when trying to upload.
The script console of Web+ shows no output whatsoever.
A Web+ bug after all?

**Comment by aplgithub** [comment]
I suspect that it would be; I think if it is working on Firefox and Chrome then it is most likely a Web+ issue.

**Comment by humdingerb** [comment]
OK, thanks. I've moved the bugreport to https://dev.haiku-os.org/ticket/13065
