### ISSUE TITLE
Icons/screenshots are not inherited between archs

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#114]
x86_64 QupZilla page doesn't display resources available on x86_gcc2

https://depot.haiku-os.org/#/pkg/qupzilla/haikuports/1/8/7/-/1/x86_64
https://depot.haiku-os.org/#/pkg/qupzilla_x86/haikuports/1/8/6/-/1/x86_gcc2

**Comment by aplgithub** [comment]
These are two separate packages with two completely different names.

**Comment by diversys** [comment]
Now that we have a lot more packages this became quite a problem as I have to add icons/screenshots/localization for the same apps. Maybe there is a way to import resources somehow?

**Comment by aplgithub** [comment]
Hi @diversys ; I am not clear why there are two different names for the same package?  Why does the "_x86" variant need to exist?  The same package can exist with two different architectures in two different repositories under the same name can they not?

**Comment by aplgithub** [comment]
@diversys ; did you find out why there are "_x86" variants of the package names?

**Comment by diversys** [comment]
On gcc2h there is only QupZilla_x86 as it can only be compiled with gcc5:
https://github.com/haikuports/haikuports/blob/master/www-client/qupzilla/qupzilla-1.8.9.recipe#L24

**Comment by aplgithub** [comment]
So by giving it the "_x86" prefix does this somehow trigger the package name change?  I don't know the recipe system too well.

**Comment by aplgithub** [comment]
Provide a linkage between packages to *copy* the data changes in one package over to the other.

**Comment by diversys** [comment]
> So by giving it the "_x86" prefix does this somehow trigger the compile to use gcc5 on the hybrid build system? I don't know the recipe system too well.

This is exactly how it works.

**Comment by aplgithub** [comment]
Is there no other way to trigger the compile to use gcc5?  The reason I ask is that having two different identifiers for the same package is quite messy to deal with.

**Comment by diversys** [comment]
AFAIK this is the only way for haikuporter to use gcc5.

**Comment by aplgithub** [comment]
(as seen on the mailing list) There is some new behaviour relating to "subordinate" packages.  You can find out more about this in the [documentation](https://depot.haiku-os.org/__docs/ch02.html#d0e241) under "Subordinate Packages".  When a subordinate package is imported, the meta-data resources are copied over.  Also when meta-data is edited in the main package, those changes also occur in the subordinate packages.

**Comment by diversys** [comment]
x86_64 QupZilla page still doesn't have screenshots from x86_gcc2.

**Comment by aplgithub** [comment]
Try edit ```qupzilla``` and you will see that ```qupzilla_x86``` also changes.

**Comment by diversys** [comment]
I tried to edit Localization and Popularity, hoping it would trigger import but it didn't.

**Comment by aplgithub** [comment]
I assume you mean that you performed the following steps;

* Change HDS language to X
* View package ```qupzilla```
* Edit localization for language X
* Save the changes
* View package ```qupzilla_x86```

*Expected* : The localization changes are able to be viewed on ```qupzilla_x86```
*Actual* : The localization changes were not able to be viewed on ```qupzilla_x86```

Can you confirm this is what you mean?

---

The prominence (popularity) is not copied across to subordinate packages because this is controlled at a repository level and I don't think that makes sense.  You will need to edit each package version's prominence.

**Comment by diversys** [comment]
Apart from that I didn't change HDS language this are exactly my steps.

**Comment by aplgithub** [comment]
Hi; I've just done that again now both in production and in my local system and it transfers the edited localization from ```qupzilla``` to ```qupzilla_x86``` fine.  I don't know what to do other than to ask you to produce screenshots or a video of you doing it?

**Comment by aplgithub** [comment]
There is a problem that categories are not copied to the subordinate package.  I will need to add this in.

**Comment by diversys** [comment]
I think I first tried to edit `qupzilla_x86` expecting it to be copied to `qupzilla`. Does it work in both directions or only from `x86_64` to  `x86_gcc2`?

**Comment by aplgithub** [comment]
Hello; when you edit ```qupzilla``` then the data will be carried over to ```qupzilla_x86```.  It does not get carried over in the other direction.

**Comment by diversys** [comment]
Ah, that explains it then.

**Comment by aplgithub** [comment]
Hello @diversys; the package categories should now be relayed to the "_x86" variant.  This change is now deployed.
