### ISSUE TITLE
RSS feeds don't work

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#122]
I have to admit that I don't use RSS feeds too much...
I tried this generated URL:
https://depot.haiku-os.org/feed/pkg.atom?natlangcode=de&limit=25&types=CREATEDPKGVERSION,CREATEDUSERRATING

Doesn't work in QupZilla or fRiSS under Haiku.
Is something amiss, or did I do something wrong.

Also, the package summaries (and possibly titles) don't appear to be the translations.

**Comment by aplgithub** [comment]
I've fixed the issue with the package summaries not showing localized data (revision fce939388881f7656f4bac6bd3314025e5f8977c) but I'm not too sure about the compatibility with "fRiSS" or "QupZilla".  I assume that those browsers only support RSS rather than the Atom format.  I can perhaps also support the feeds in RSS format in the future.

**Comment by humdingerb** [comment]
I think you might be right.
This RSS works with QupZilla:
https://en.wikipedia.org/w/index.php?title=Special:NewPages&feed=rss

This ATOM does not:
https://en.wikipedia.org/w/index.php?title=Special:NewPages&feed=atom

**Comment by aplgithub** [comment]
I just modified (81810a57745bad1310d314b1b06d1a5dc9cc61ac) HDS to output ATOM as well as RSS, but it doesn't look like QupZilla renders the RSS from that either.  It will go out in the next deployment so perhaps you can see if you can have a look then.  Just swap the extension ".atom" for ".rss".

**Comment by aplgithub** [comment]
Hi Humdinger; can you please check this one again.

**Comment by humdingerb** [comment]
Sorry, I forgot about that...
Using ".rss" instead of ".atom" now shows the feed in QupZilla, with the right locale and everything! Couldn't test with fRiss, as that seems to be broken at the moment (probably needs just a rebuild).
Thanks for the fix!

**Comment by aplgithub** [comment]
Cool - that's good.
