### ISSUE TITLE
unable to find an entity for; repositorySource 

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#123]
Clicking URL at https://depot.haiku-os.org/#/repository/haikuports/source/haikuports_x86_64 shows unable to find an entity for; repositorySource

**Comment by aplgithub** [comment]
Do you mean you open that URL in a browser and you get a plain-text page shown that reads...?

> unable to find an entity for; repositorySource

Can you let me know the browser or browsers where you see this?  I am trying on Firefox as well as Chrome on MacOS-X and don't seem to see this issue here.

**Comment by diversys** [comment]
That is correct. I am also trying trying on Firefox and Chrome on macOS.

**Comment by diversys** [comment]
Correction: Firefox says:

> File not found
> Firefox can’t find the file at https://depot.haiku-os.org/repositorySource.url.
