### ISSUE TITLE
Huge image size causes error

### ISSUE THREAD

**Issue by kainjow** [aplgithub/haikudepotserver#126]
Take this URL:

https://depot.haiku-os.org/__pkgscreenshot/7e9efd65-ff05-45e6-bbb5-5635d01f6c79.png?m=1486504723545&tw=213&th=240

and modify th to be 10000:

https://depot.haiku-os.org/__pkgscreenshot/7e9efd65-ff05-45e6-bbb5-5635d01f6c79.png?m=1486504723545&tw=213&th=10000

You'll get:

> Something has gone wrong with your use of this web application.

**Comment by aplgithub** [comment]
Hello Kevin; The code causing this is to be seen in ```PkgScreenshotController#handleHeadOrGet(..)```.  If you run with ```curl -v ...``` you will get;

```
< HTTP/1.1 415 the target width or height must be greater than zero and less than the maximum
< Date: Mon, 27 Feb 2017 08:46:21 GMT
< Server: Jetty(9.3.13.v20161014)
< Content-Type: text/html;charset=utf-8
< Content-Length: 1959
```

Can you expand on what is wrong in this scenario?

**Comment by kainjow** [comment]
Maybe it should automatically use the maximum size then, instead of dying?

**Comment by aplgithub** [comment]
It is not failing - it is intentionally signalling an error.  Check out [this](https://depot.haiku-os.org/__docs/ch13.html#d0e1924) document under "Get Screenshot Image".
