### ISSUE TITLE
Password reset won't work

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#129]
See this [forum post](https://discuss.haiku-os.org/t/resetting-depot-haiku-os-org-password/5454):
"I am trying to reset my depot passwod. While I receive an email after hitting "reset a forgotten passwrd", but the received link puts me back to the main depot page."

Just tried it myself. He's right.

**Comment by aplgithub** [comment]
Hi Humdinger -- this fix should be deployed in 1.0.82 now.  Can you ask the person with the issue to check again if you have contact with them.

**Comment by humdingerb** [comment]
I posted to that forum thread and have tested myself. I does indeed work again, as does that other issue with the broken link at the fallback localization page. Thanks for the quick fix!
