### ISSUE TITLE
Bulletpoints layout

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#131]
layout seems to be a bit off for these bulletpoints
- All versions
- Visit web site
- Download package 'hpkg' file
- View localizations bundled in this package
- Changelog

**Comment by diversys** [comment]
https://depot.haiku-os.org/libass

Google Chrome 58.0.3029.96 (64-bit) on macOS 10.12.4 (also in Incognito mode)
Safari and Firefox seems to render it fine.

<img width="911" alt="screen shot 2017-05-11 at 15 32 36" src="https://cloud.githubusercontent.com/assets/1316513/25949444/42ade6d6-3660-11e7-9b11-969f934901c9.png">

**Comment by aplgithub** [comment]
Strangely if you then open the debug tools, the layout is looking normal.  I suspect this bug may one for Chrome rather than HDS.

**Comment by aplgithub** [comment]
How's that looking for you now?

**Comment by diversys** [comment]
Looks good now, thanks!
