### ISSUE TITLE
Drop x86 repo

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#136]
There are no more nightlies for x86 (gcc5 only) arch. Now that there are only two arches left maybe a simple radio button can me added instead of popup menu selector. Saves one click, you know :)

**Comment by aplgithub** [comment]
Hi @diversys ; There is a chance in the future to have ARM etc.. in there so I'll leave the architecture as a drop-down at least for the time being.  I'll check on the mailing list before removing the "x86" architecture in case anybody has any concerns.
