### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kallisti5** [aplgithub/haikudepotserver#137]
Saw a java crash on the production machine.
[depot-crash.txt](https://github.com/aplgithub/haikudepotserver/files/1268035/depot-crash.txt)
See logs attached.

**Comment by aplgithub** [comment]
This is just an HTTP request that is yielding a main-flow exception; the application-server will continue to operate fine.  A external agent is making an invalid [HTTP request](https://depot.haiku-os.org/__docs/ch13.html#d0e1817) to get an icon for a package.  They are missing the size parameter "s".  I could remove the trace and that would make it less noisy, but then the trace can be helpful sometimes.  Thank you for raising the issue, but I think that it is OK.
