### ISSUE TITLE
Editing fallback-localization broken (sometimes?)

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#141]
I tried to add German localizations to Noto_condensed. First the localizations wouldn't hold, reopening showed empty fields. Then that worked, but now adding to the localization transports me to the "Oh darn! Something has gone wrong with your use of this web application" page.

**Comment by aplgithub** [comment]
Turns out it was a bug in the version of the ORM that is used in HDS.  It looks like the bug is fixed in the next release so I implemented a work-around for the time being.  This is deployed now.  Can you please try again.

**Comment by humdingerb** [comment]
Thanks for the quick fix! Works now.
