### ISSUE TITLE
New packages are missing

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#142]
Some time ago I fixed qBittorrent package but still can't it in x86_gcc2 repo here.

**Comment by aplgithub** [comment]
You are not providing enough information to know what the problem is.  I have downloaded the HaikuPorts "x86gcc2" HPKR (```repo``` file) and it contains;

```
qbittorrent_x86 : 4.0.3..3 : X86_GCC2
qbittorrent_x86_source : 4.0.3..3 : SOURCE
```

In the HDS interface I see the package "qbittorrent_x86" with version "4.0.3-3 - x86_gcc2".  Could you please let me know where the issue is?

**Comment by diversys** [comment]
qbittorrent_x86 has now appeared. But virtualbox_guest_additions haven't.

**Comment by aplgithub** [comment]
The repository contains;

```
virtualbox_guest_additions : 4.3.12..1 : X86_GCC2
virtualbox_guest_additions_source : 4.3.12..1 : SOURCE
```

...and indeed it was not in HDS, but after I triggered an import it is there.  You can find out more about triggering an import using a remote url [here](https://depot.haiku-os.org/__docs/ch13.html#api-importrepositorydata).  It would be good if the HaikuPorts building system were able to trigger this process each time it releases a new build of the repository.

**Comment by diversys** [comment]
@mmlr could you set up a trigger?

**Comment by mmlr** [comment]
I was not aware that this was needed, thanks for the heads up. I'm currently still abroad for work, but I'll look into it in a couple of hours. Seems straight forward in any case. I presume the repository code would be HaikuPorts in this case?

**Comment by aplgithub** [comment]
Hello @mmlr; You can get a list of the repositories' and repository-sources' codes through the human-facing interface [here](https://depot.haiku-os.org/#!/repositories).  You can also get a great big list of all of the repositories and their details in a machine-readable format [here](https://depot.haiku-os.org/__repository/all-en.json.gz).  Let me know if you need further help.  @diversys ; can we close this ticket?

**Comment by diversys** [comment]
Sure, let's do that :)

**Comment by mmlr** [comment]
Triggers have been added requesting ```__repository/haikuports/source/haikuports_x86_gcc2/import``` and ```__repository/haikuports/source/haikuports_x86_64/import``` respectively.

**Comment by aplgithub** [comment]
Great thanks!
