### ISSUE TITLE
HaikuDepot doesn't receive captchas

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#148]
This is under Haiku hrev51856.

When trying to register a new  account in HaikuDepot, the registration window lacks a captcha question. When entering a random number and clicking "Create", an alert says:

"It was not possible to contact the web service."

That's why I assume an issue with HDS. Or is it a HaikuDepot bug?

**Comment by aplgithub** [comment]
I can reproduce the problem locally.  I have a [pull request](https://review.haiku-os.org/#/c/103/) with more debugging in place however it seems to work with the extra debugging.  Can you please grab that, compile a HaikuDepot and then run it with ```-v debug```.  Let me know if the captcha appears for you.  Please don't proceed with adding a test user as it will create test data in the production system.

**Comment by humdingerb** [comment]
With the patch applied, I get the captcha. This is the output:

will make json-rpc request to [https://depot.haiku-os.org/__api/v1/captcha]
did receive json-rpc response http status [200] from [https://depot.haiku-os.org/__api/v1/captcha]

**Comment by aplgithub** [comment]
OK great; then I will assume that if the patch goes through it should be OK.
