### ISSUE TITLE
HDS not updating with newly built packages

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#149]
HDS seems to be stuck at 9th of May 2018. New/updated packages from the buildbots don't appear at the HDS site.
As an example, I was looking for the tipster-1.1.0-1 packages built on 11th of May, see http://kitchen.haiku-os.org/master/x86_gcc2/?buildrunDir=1176&viewMode=expanded

**Comment by aplgithub** [comment]
The fix is in place ready to go, but will need to be deployed (hopefully tomorrow)
