### ISSUE TITLE
Container healthcheck

### ISSUE THREAD

**Issue by kallisti5** [aplgithub/haikudepotserver#150]
Might be nice if we ever want or need to scale the number of haikudepotserver nodes:

HEALTHCHECK --interval=30s --timeout=10s CMD curl -f http://localhost:8080/__metric/healthcheck

Adding that to the Dockerfile (should) let docker monitor the container's health like our s3 servers:
```
3a85e95986c7        minio/minio                       "/usr/bin/docker-e..."   20 minutes ago      Up 20 minutes (healthy)   9000/tcp                                   infrastructure_cdn_1
```

**Comment by aplgithub** [comment]
Does having this configured mean that the Docker environment will take any action like trying to re-spawn a new instance in the case that the health-check fails?  If so, I would be a bit reluctant early on because it may make it a bit more difficult to diagnose issues.

**Comment by kallisti5** [comment]
"if the health check fails, the docker container is restarted"

The logs shouldn't be purged or anything, so we don't lose troubleshooting information.
