### ISSUE TITLE
Reports show entries with empty repository field

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#157]
I exported reports for screenshots and icons etc. I found a few entries with an empty repository column. E.g. berometer, freecol, hodoku, jircii, micshooter, mucommander and more.

What's going on here?

**Comment by aplgithub** [comment]
Those packages are present in the HDS system and *might* still have an icon, but are no longer present in any repository.  This can happen under the following circumstances;

* A repository existed once and caused some packages to be loaded into HDS, but then the repository was disabled.
* A package was in a repository, but was then removed from the repository.  On a subsequent load of the repository's HPKR data, the package was disconnected from the repository and was left with no associated repository.

**Comment by humdingerb** [comment]
Ah, ok. Then I'll just ignore those and you can close this ticket. :)
