### ISSUE TITLE
Clean URLs

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#3]
Current URLs look too untidy:
https://depot.haiku-os.org/#/pkg/openjdk_x86/1/7_u80_b02/-/-/1/x86_gcc2?bcguid=bc2-VWOL

https://depot.haiku-os.org/openjdk (is ARCH even needed here?) pointing to the latest version of the package would look much cleaner.

Also, it is not possible to open https://depot.haiku-os.org/#/pkg/openjdk_x86 to see which other versions are around.

**Comment by aplgithub** [comment]
Now most of the important links are *both* able to do a right-click-and-open-tab *and* are "single page"!  Let me know if I have missed any links that you care about and please raise an issue in GitHub if you see any anomalies.

**Comment by diversys** [comment]
Hmm, this issue is not fixed though. HDS doesn't use clean URLs..

**Comment by aplgithub** [comment]
Sorry my mistake; I must have skim-read it and mis-interpreted the issue.  I will leave this closed as it is already in git comments and I will open a new issue #8 that covers the one that you have reported.
