### ISSUE TITLE
Stop filtering ratings

### ISSUE THREAD

**Issue by luroh** [aplgithub/haikudepotserver#30]
There seems to be a slightly annoying discrepancy between how HaikuDepot and HDS are presenting ratings (stars). HDS seems to have a filter requiring a certain number of user ratings to have occurred before presenting an average rating while HaikuDepot does not.

If my assumption is correct, I suggest we remove that filter in HDS. The Haiku community is very small and even a single rating can be very useful to a package maintainer. Example: the package Goonies has a single rating but looks "unrated" in HDS. The user rating in this case is a single star along with a helpful message.

**Comment by aplgithub** [comment]
Oliver; can you please deploy "haikudepotserver-1.0.33" when you get a moment.  To resolve #30, can you please set the configuration parameter;

```
userrating.aggregation.pkg.minratings=1
```

Then authenticate as root and go "Menu" -> "Root Operations" -> "Derive and store user ratings for all packages".  This will re-calculate the user ratings so they match those that appear to be being used in the desktop application.  It may take some time to execute.

**Comment by aplgithub** [comment]
Note; no code changes required.
