### ISSUE TITLE
Use HSD logo to go to main page

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#50]
...also reset search, arch and other filters on click

**Comment by aplgithub** [comment]
Hi @diversys; I can generally go to another page and then use the top-left logo to navigate back to the home page.  Is this what you are reporting as the problem?  If so, what browser are you seeing this problem in?

The problem where you are already on the home page and click on the top left logo and it does not reset the search specifications; I can reproduce that problem.

**Comment by diversys** [comment]
Hi, I can't seem to find a page I had this problem now or maybe I was just using some other browser. So you can ignore the first problem for the time being :)
