### ISSUE TITLE
Add Haiku master repo

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#51]
http://download.haiku-os.org/haiku-repositories/master/x86_gcc2/current

**Comment by aplgithub** [comment]
Hi; I'm going to start on (slowly) modifying the repository - pkg relationship in the database and application-server in order to better accommodate "other repositories".  This is going to take a little while, but afterwards it will be much easier to add in other repositories like this.

**Comment by aplgithub** [comment]
This should be possible now.  Can you please get me all of the URLs (eg; [HaikuDepot](https://depot.haiku-os.org/#/repository/haikuports)) to pull HPKRs from.  I wonder what is the best logistical name for this?  Just "Haiku" or "Haiku-R1" or ...?

**Comment by waddlesplash** [comment]
Just "Haiku". Eventually there will be a "Haiku-Beta1" and "HaikuPorts-Beta1" repo but those don't exist yet.

**Comment by aplgithub** [comment]
Hi @waddlesplash; do you happen to have the list of "hpkr" URLs for that?

**Comment by waddlesplash** [comment]
Yes, the pattern is:
```
http://packages.haiku-os.org/haiku/master/$ARCH$/current/
```
Replace $ARCH$ with the architecture (e.g. x86). The "repo", "repo.info", etc. files are all in that directory.

**Comment by diversys** [comment]
HaikuDepot still doesn't get info from Haiku repo:

"No package info for haiku"

**Comment by aplgithub** [comment]
HaikuDepot will pull information for the "haikuports" repository only; see changes in TRAC 12216.  HaikuDepot needs to be updated so that it will request information for the Depots that it / the environment has configured.  This work is yet to be done on the desktop application.
