### ISSUE TITLE
Show category name in breadcrumb navigation

### ISSUE THREAD

**Issue by richienyhus** [aplgithub/haikudepotserver#55]
When navigating packages via category lists, the breadcrumb navigation adds links back to previously viewed packages and categories, however the categories are all recorded as "Home".

It would be more useful if they were displayed with the name of the category instead.

What it should be like:
Home > Album > Graphics > Marble> Productivity > BePDF > System and Utilities > ArmyKnife > etc

What it currently is:
![2015-05-21 22 13 24](https://cloud.githubusercontent.com/assets/3889965/7746415/2ce86534-0006-11e5-984b-cb6b9c5a9c2b.jpg)

**Comment by aplgithub** [comment]
Hi @richienyhus; do you think it might be better and perhaps more logical if, upon clicking a "category", that the navigation did not add a breadcrumb item and instead reset to home with that package category selected?

**Comment by aplgithub** [comment]
Should be sorted in the next release.
