### ISSUE TITLE
Focus search field after page load

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#59]

**Comment by diversys** [comment]
Also focus it after clicking logo/title

**Comment by aplgithub** [comment]
Should be working in 1.0.49.

**Comment by diversys** [comment]
Tested non-production server and my last comment still applies.

**Comment by aplgithub** [comment]
Hi @diversys; OK a bit more background would be helpful.  I've been playing around some more, but only now realize you mean that this is when you are already on the home page.  Something like this would be good;

# navigate to home page
# observe the "search field" has focus
# click on the title from the home page
# expected the "search field" to have focus, but focus is lost
