### ISSUE TITLE
Icons don't look good on HiDPI displays

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#62]

**Comment by aplgithub** [comment]
Do you mean package icons or iconography that is part of the application itself?

**Comment by diversys** [comment]
I meant package icons of course :)

**Comment by aplgithub** [comment]
...I was going to say!

**Comment by aplgithub** [comment]
Should be solved in version 1.0.48

**Comment by diversys** [comment]
Actually, I didn't realise there were other icons in the application itself. If they in fact exist they should be adjusted as well.

**Comment by diversys** [comment]
Is anything possible to do with screenshots?

**Comment by aplgithub** [comment]
> I didn't realise there were other icons in the application itself.

I am not too sure what you mean there.

Can you please open a different ticket for the screenshots and I will take a look into that.
