### ISSUE TITLE
HVIF Icon upload fails

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#64]
Since the latest version, icon upload fails. Pressing the submit button, the screen goes grey, but the three progress circles don't animate as usual. Uploading screenshots works though.

Just found out: uploading just the PNG icons works. So uploading the HVIF seems to be the issue.

**Comment by humdingerb** [comment]
Luroh was able to also upload the HVIF with Firefox under Linux. So it may just be some issue with QupZilla under Haiku? Would be strange, though, no?

**Comment by aplgithub** [comment]
Hi @humdingerb; I've just tried to populate an HVIF on the test system for the package "groff".  It seemed to work fine for me with a fairly recent WebPositive.  Can you please open the "Script Console" and see if there is any diagnostic information there which might point to the issue?

**Comment by humdingerb** [comment]
Unfortunately, my Web+ locks up when I click "Edit icons". But here is what QupZilla's console spits out:

http://postimg.org/image/vl39isg4v/
http://postimg.org/image/5nlnj76dj/

Hope that helps.

**Comment by diversys** [comment]
Still fails in QupZIlla http://i.imgur.com/zDrEMNV.png
Web+ locks up at exactly the same point, probably related to this bug: https://dev.haiku-os.org/ticket/12083

**Comment by humdingerb** [comment]
On 3 June 2015 at 14:32, diversys <notifications@github.com> wrote:

> Still fails in QupZIlla http://i.imgur.com/zDrEMNV.png
>
Works here... with QupZilla 1.8.6.

Regards,
Humdinger

--
Got a working haikuports recipe?
Contact me to add it to HaikuDepot.
https://bitbucket.org/haikuports/haikuports

**Comment by aplgithub** [comment]
@diversys; can you please re-test on QupZilla.

**Comment by diversys** [comment]
Seems to work now. Thanks! :)
