### ISSUE TITLE
_devel descriptions should inherit from their localized 'normal' package

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#66]
The description of _devel packages are pretty much always the same as for the standard package. Only to the Summary a "(development files)" is added. Therefore, the _devel
Summary/Description should inherit the contents from the localized version and have the localized "(development files)" added automatically to the Summary.

**Comment by diversys** [comment]
Would it possible to do the same for icons from 'normal' packages?

**Comment by aplgithub** [comment]
Hi @diversys; yes should be possible - would you like to open a new ticket for that one too?
