### ISSUE TITLE
Add changelog information

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#70]
HaikuDepot has Changelog tab which should probably be downloaded from HDS. Some software provides direct link to a its changelog (e.g. https://raw.githubusercontent.com/FFmpeg/FFmpeg/master/Changelog), so maybe HDS could pass that?

**Comment by aplgithub** [comment]
Hi @diversys; can you please elaborate on the mechanic through which you envisage HDS would obtain the change log data for a specific version?

**Comment by diversys** [comment]
Don't think it's possible. Probably showing full change log is the only option

**Comment by aplgithub** [comment]
I am wondering if this is best stored at the package level or at the package version level?  Any thoughts on that?  I am thinking that it may be best to maintain one big hunk of text as an on-going change log on a package to keep it relatively straight forward.

**Comment by aplgithub** [comment]
Is in the 1.0.54 release.
