### ISSUE TITLE
Show stats information

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#71]
It would be useful to see what apps are the most popular by having a download counter per package.

**Comment by aplgithub** [comment]
Hi @diversys; Can you describe the mechanic by which that would be incremented in HDS?

**Comment by aplgithub** [comment]
I can't see how this can be implemented unless HDS itself is the source of the HPKGs?

**Comment by diversys** [comment]
Maybe using some info from https://web-stats.haiku-os.org ?
