### ISSUE TITLE
Show translation status in package search results

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#72]
It'd be nice if one could navigate through the package search results (you know, the normal table of all the packages) and see which ones have a translation of their summary/description already. Maybe a little flag in the table heading of that column and only for the language that is set for the user.

**Comment by aplgithub** [comment]
(c.f. @humdingerb) should no longer be necessary as it can easily be seen by looking at the summary shown in the list view.  A happy side-effect of showing the summary in the list.
