### ISSUE TITLE
haiku_loader package cannot be found by searching for 'haiku'

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#75]

**Comment by waddlesplash** [comment]
I can see it, but I have to check "Haiku" in the repositories menu. Maybe Haiku should be a default repository?

**Comment by diversys** [comment]
I can't find it even after enabling "Haiku" in the repositories menu. And yes, Haiku should be a default repository.

**Comment by diversys** [comment]
I somehow missed there was the second page. Sorry for the noise.
But yeah, Haiku should be a default repository.
