### ISSUE TITLE
Provide download links for packages

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#81]
Some users have no internet connection in Haiku but still want to install certain packages.
A bunch of such users asked me why HDS doesn't provide download links.

**Comment by aplgithub** [comment]
Yes that is a good point; should not be too tricky.

**Comment by diversys** [comment]
Thanks! Would it be possible to also provide links to dependencies?

**Comment by aplgithub** [comment]
links to dependencies would require the HPKG to be parsed as well; probably do-able at some point.
