### ISSUE TITLE
Package repos naming convention

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#83]
It would be more consistent to follow existing naming convention wrt repo names:
See: http://packages.haiku-os.org/haikuports/master/repo/
and  http://download.haiku-os.org/haiku-repositories/master/

x86
x86_64
x86_gcc2

**Comment by aplgithub** [comment]
Do you mean the repository sources?

**Comment by diversys** [comment]
Yep, https://depot.haiku-os.org/#/repository/haiku

**Comment by aplgithub** [comment]
They need to be unique between depots.

**Comment by diversys** [comment]
How about %reponame_arch%?
haikux86 -> haiku_x86
haikux86gcc2 ->haiku_x86_gcc2
haikux8664 -> haiku_x86_64
