### ISSUE TITLE
Packages from Haiku repo are outdated

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#88]

**Comment by aplgithub** [comment]
Ideally the Haiku build system would [trigger](https://depot.haiku-os.org/docs/ch12.html#api-importrepositorydata) the import process itself, but it would also be possible to 'cron' such a trigger into HDS each day to pull in updates.

**Comment by diversys** [comment]
Interesting. How does it work for haikuports repos?

**Comment by aplgithub** [comment]
I'm not entirely sure, but I think the HPKR build process triggers HDS to re-import.

**Comment by aplgithub** [comment]
As a "worst case" handling for this, HDS will do a daily trigger to pull in any updates (next version)
