### ISSUE TITLE
Add Guest One's repos

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#90]
http://haiku.uwolke.ru/repo/binaries-x86_gcc2
http://haiku.uwolke.ru/repo/java-ports

**Comment by aplgithub** [comment]
Need to sort out #83 first then should be easy.

**Comment by diversys** [comment]
Should be possible now?

**Comment by aplgithub** [comment]
I've loaded in the "x86_gcc2" repository.  The Java one has an invalid URL on a package of "hhttp://www.projectlibre.org/".  If you have contact with the packagers, can you please ask them to fix this then I will try again.

**Comment by diversys** [comment]
The package in question is now fixed.

**Comment by aplgithub** [comment]
This is done now and has been imported successfully.
