### ISSUE TITLE
Download links for packages are broken

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#92]
Download links look like this https://depot.haiku-os.org/__pkgdownload/armyknife/haikuports/4/3/0/-/3/x86_gcc2/package.hpkg

Would it be possible to show direct download links instead?

**Comment by aplgithub** [comment]
That should be working as-deployed now.

**Comment by diversys** [comment]
Thanks! What about showing direct links?

**Comment by aplgithub** [comment]
The HaikuDepot repository is served through file:/// URLs so it is hitting HDS and then either;

* Redirecting to the actual internet-visible repository
* Proxying the data through HDS
