### ISSUE TITLE
haikuports repo seems to be outdated

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#93]
Recently added package is not visible at https://depot.haiku-os.org/fasm

**Comment by aplgithub** [comment]
It _appears_ that the trigger to import the repository from the HaikuPorts build is no longer happening.  Are you in communications with the people doing the work on the HaikuPorts build system?  If so, can you please tell them to see if their build system is calling [this](https://depot.haiku-os.org/docs/ch12.html#api-importrepositorydata) after re-building the repository?

**Comment by aplgithub** [comment]
The next version will update from active repositories at least once a day to avoid this sort of problem; although this does constitute polling and it would be more elegant if the repository-builders could raise the event that the HDS system ought to re-import the repository data.

**Comment by jessicah** [comment]
Not sure if the URL changed or not, but the URLs in the git post-commit hook was wrong. I've updated the script, so it should be working now...

**Comment by aplgithub** [comment]
Thanks for that.

**Comment by diversys** [comment]
Seems to be back. Packages added in http://cgit.haiku-os.org/haiku/commit/?id=hrev49664 are not visible in HDS.

**Comment by aplgithub** [comment]
I seem to be able to see the following in the import-log from the HPKR and also in the user interface...

* album-0.9.4-1
* clipdinger-0.4-2
* lnlauncher-1.1.2-4
* netpulse-0.2.3-5

...can you please clarify the nature of the issue?  Where are you seeing the actual problem?

**Comment by diversys** [comment]
Yes, I was going to comment that I can see them today. However, yesterday I waited for a few hours for the packages to show up and they weren't there.

**Comment by aplgithub** [comment]
Hi; looking at the logs, the only repository imports I can see over the last week or so are at "01:24" (GMT0) which I assume is the daily process configured in cron.  You will need to speak with the people working on the repository build process and ask them if they can use [this] (https://depot.haiku-os.org/docs/ch12.html#api-importrepositorydata) API to trigger the rebuild for a specific repository after the repository is re-built.

For example, to trigger an import across all architectures for HaikuPorts one would call with GET method on [this](https://depot.haiku-os.org/repository/haikuports/import).  I just checked this now and it is working.
